# -*- coding: utf-8 -*-
"""Music Recommendation App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7D_ytveg0rAQmEQnoLnNeOTHwWizXSN
"""

import streamlit as st
import requests
import json

# --- Page Configuration ---
st.set_page_config(
    page_title="AI Music Explorer",
    page_icon="🎵",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# --- API Call Function ---
# Use Streamlit's cache to avoid re-running the API call for the same query
@st.cache_data
def fetch_popular_music(query, api_key):
    """
    Fetches popular music data from the Gemini API.
    This function corresponds to the fetchPopularMusic async call in the React app.
    """
    if not query:
        return None, "Please enter a location."

    # The API endpoint and payload are similar to the React version
    api_url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-05-20:generateContent?key={api_key}"

    user_prompt = (
        f'Find the top 10 most popular songs in {query}. '
        'Respond with ONLY a valid JSON array of objects, where each object '
        'has a "title" and "artist" key. Do not include any other text, just the array.'
    )

    payload = {
        "contents": [{"parts": [{"text": user_prompt}]}],
        "tools": [{"google_search": {}}]
    }

    headers = {'Content-Type': 'application/json'}

    try:
        response = requests.post(api_url, headers=headers, data=json.dumps(payload))

        # Check for a successful response
        if response.status_code == 200:
            result = response.json()
            json_text = result.get("candidates", [{}])[0].get("content", {}).get("parts", [{}])[0].get("text", "")

            if json_text:
                # Clean the response to ensure it's valid JSON
                cleaned_json_text = json_text.replace("```json", "").replace("```", "").strip()
                tracks = json.loads(cleaned_json_text)
                return tracks, None
            else:
                return None, "No valid content received from the AI. The region might not be recognized."
        else:
            return None, f"API call failed with status: {response.status_code}. Details: {response.text}"

    except requests.exceptions.RequestException as e:
        return None, f"A network error occurred: {e}"
    except json.JSONDecodeError:
        return None, "Failed to decode the JSON response from the AI. The format might be incorrect."
    except Exception as e:
        return None, f"An unexpected error occurred: {e}"


# --- UI Rendering ---

# Header Section
st.markdown("""
    <div style="text-align: center;">
        <h1>🎵 AI Music <span style="color: #6366F1;">Explorer</span></h1>
        <p style="color: #9CA3AF; font-size: 1.1rem;">
            Find real-time popular music from anywhere in the world.
        </p>
    </div>
""", unsafe_allow_html=True)
st.markdown("---")


# Search Bar
search_query = st.text_input(
    "Search Location",
    "",
    placeholder="Enter a country or city (e.g., Japan, London)...",
    label_visibility="collapsed"
)


# Main Content Area
if search_query:
    st.subheader(f"Trending in {search_query}")

    # Fetch API Key from Streamlit Secrets
    try:
        api_key = st.secrets["GEMINI_API_KEY"]

        # Display a spinner while fetching data
        with st.spinner('Searching for top hits...'):
            tracks, error = fetch_popular_music(search_query, api_key)

        if error:
            st.error(f"An error occurred: {error}")
        elif tracks:
            # Display results in a two-column layout
            cols = st.columns(2)
            for i, track in enumerate(tracks):
                with cols[i % 2]:
                    # Create a card-like display for each track
                    st.markdown(f"""
                        <div style="background-color: #1F2937; border-radius: 10px; padding: 1rem; margin-bottom: 1rem; display: flex; align-items: center;">
                            <img src="https://placehold.co/80x80/1D4ED8/FFF?text={track.get('artist', '...').split(' ')[0]}" style="border-radius: 5px; margin-right: 1rem;">
                            <div>
                                <h3 style="margin: 0; color: white;">{track.get('title', 'No Title')}</h3>
                                <p style="margin: 0; color: #9CA3AF;">{track.get('artist', 'No Artist')}</p>
                            </div>
                        </div>
                    """, unsafe_allow_html=True)
        else:
            st.warning("No popular music found for this location. Please check the spelling or try another region.")

    except KeyError:
        st.error("GEMINI_API_KEY not found in Streamlit Secrets. Please add it to your secrets file.")

else:
    # Initial placeholder content
    st.info("Enter a location above to discover the most popular songs.")

# Footer
st.markdown("---")
st.markdown('<p style="text-align: center; color: #9CA3AF;">Powered by AI</p>', unsafe_allow_html=True)